FROM python:3.6

RUN  apt-get update -y && \
    apt-get upgrade -y 

# API
RUN mkdir -p /usr/src/package
COPY ./package /usr/src/package
WORKDIR /usr/src/package
RUN pip install -e .

# Start processes
CMD ["python3", "-m", "swagger_server"]