version: '3'

services:
  student-db-api:
    build:
      context: .
      dockerfile: Dockerfile_dev
    ports:
      - "8000:5000"
    env_file:
      - api.env
    depends_on:
      - mongodb
    networks:
      - backbone

  mongodb:
    image: mongo:3.6
    command: mongod
    ports:
      - 27017:27017
    env_file:
      - mongo.env
    networks:
      - backbone

networks: 
  backbone:
    driver: bridge
